name: Build the React application and create a docker image
on:
  push:
    branches:
      - 'main'
jobs:
  build-container:
    name: Build the React application and create a docker image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout the source code
        uses: actions/checkout@v3.1.0
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT_TOKEN }}
      -
        name: Publish to GitHub Packages
        uses: docker/build-push-action@v3.1.1
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest, ghcr.io/${{ github.repository }}:${{ github.run_number }}
